extends: default
ignore: |
  .git/
rules:
  line-length:
    max: 200
    allow-non-breakable-inline-mappings: true
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
